### ISSUE TITLE
Functionality to calculate z-scores

### ISSUE THREAD

**Issue by timcadman** [thlytras/rspiro#1]
Hi there,

Is it possible to add the functionality to also produce GLI z-scores?

Many thanks,

Tim

**Comment by nshrine** [comment]
Someone has done it in this fork
https://github.com/florihalbeisen/rspiro

**Comment by thlytras** [comment]
Thanks for pointing this out. It will be in my todo list (along with adding further equations).

**Comment by timcadman** [comment]
Great thanks

**Comment by thlytras** [comment]
As the package now calculates z-scores (since merge commit 449de04, on 19 Jan 2020), I'm closing this issue. Thanks for raising it.

**Comment by timcadman** [comment]
Hi there,

Apologies if I'm missing something, but I've downloaded the latest version of the package (showing as 0.2in sessionInfo() ) the function "zscore_GLI" is not found. Any ideas?

cheers

**Comment by thlytras** [comment]
No, it's there in the code and exported normally. I also scrubbed the package from my system and reinstalled from github, and the function is there and usable.
Do make sure you have not misspelt it in your code, and do make sure you're not accidentally use some older version (e.g. system-wide vs in your user account).

**Comment by timcadman** [comment]
Apologies, I've got this working now. Thanks for a great package!

cheers
