### ISSUE TITLE
'setInternet2' is defunct

### ISSUE THREAD

**Issue by mgierdal** [thlytras/rspiro#11]
_R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)_

I tried to install rspiro package per your instructions and got an error:
`Installation failed: 'setInternet2' is defunct.`

I It may be related to similar issue [elsewhere](https://github.com/r-lib/remotes/issues/250).

Thanks!

**Comment by thlytras** [comment]
You are using a very old R installation, and experiencing a bug with another package (not rspiro) which long has long been fixed (3 years ago). I can confirm `install_github()` works fine with R version 4.1.

Please update your R installation.
