### ISSUE TITLE
there should be no default value for sex and ethnicity

### ISSUE THREAD

**Issue by aminadibi** [thlytras/rspiro#13]
Thanks for the nice package. Might I suggest:

1. Renaming the "gender" input to "birth sex"? "Gender" might be misunderstood as gender identity. What reference value formulas have is sex assigned at birth. 
2. Removing default values for sex and ethnicity. There is no reason to assume, by default, that the patient is a white male. Having a default might prevent users from noticing erroneous input and increase the chance of bias. 

Thanks!

**Comment by thlytras** [comment]
Both good points, but I'd hate to make API changes that would break old code.
I can probably change 'gender' to 'search' though, while retaining the gender= argument for compatibility. I'll get to it at some point.

**Comment by thlytras** [comment]
Both good points, but I'd hate to make API changes that would break old code.
I can probably change 'gender' to 'search' though, while retaining the gender= argument for compatibility. I'll get to it at some point.
