### ISSUE TITLE
Reference values using JRS 2014

### ISSUE THREAD

**Issue by kinnersleyn** [thlytras/rspiro#14]
Hi
Is it possible to support the JRS 2014 criteria to reflect Japanese reference criteria? 
I believe that the GLI 2012 and 2022 reference datasets didn't include data from Japanese participants so it may be more relevant/accurate to have an implementation of JRS 2014 within rspiro
https://www.sciencedirect.com/science/article/abs/pii/S2212534514000288 (behind a paywall)
Thanks
Nelson

**Comment by thlytras** [comment]
Thank you for your message! JRS looks both interesting and feasible, and
I'll look into implementing it at my earliest possible convenience.

Best,
Theodore Lytras

Στις Πέμ 16 Μαΐ 2024, 14:37 ο χρήστης Nelson Kinnersley <
***@***.***> έγραψε:

**Comment by kinnersleyn** [comment]
That's great - thank you.

**Comment by thlytras** [comment]
Implemented in commit ded18aab09cb5de1a4e1b03300a8fd7310f446a9

**Comment by kinnersleyn** [comment]
Great addition. Looking forward to implementing it. Thank you
