### ISSUE TITLE
Support for GLI equations for TLCO and DLCO

### ISSUE THREAD

**Issue by kinnersleyn** [thlytras/rspiro#15]
Would it be possible to support the GLI equations for TLCO and DLCO ?
Originally published in 2017 (https://pubmed.ncbi.nlm.nih.gov/28893868/) but corrected in 2020 https://www.ers-education.org/lr/show-details/?idP=240831

**Comment by thlytras** [comment]
Implemented in commit 02b6f4a95c07d5404c44a3ead03d3230e2ab7436.

**Comment by kinnersleyn** [comment]
Great addition. Looking forward to implementing it. Thank you
