### ISSUE TITLE
Z-score formula doesn't match

### ISSUE THREAD

**Issue by Jiangnanlyu** [thlytras/rspiro#16]
Your equation for z-score is:  ((obs/M)^L-1)/(L*S))
However, the https://www.atsjournals.org/doi/suppl/10.1164/rccm.202205-0963OC/suppl_file/bowerman_data_supplement.pdf supplemental for 2022 paper is (obs-M)^(L-1)/(L*S)

**Comment by thlytras** [comment]
Thanks. I'm not sure about this discrepancy; I've used the equation from the GLI-2012 supplement (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3786581/bin/NIHMS513963-supplement-Supplementary_data.pdf), and rspiro values are the same as produced in the GLI calculator (https://gli-calculator.ersnet.org/), so I believe everything is correct. Might have been a mistake in the 2022 paper, I don't know.

**Comment by Jiangnanlyu** [comment]
but you source code title says "Convert spirometric values to z-scores using GLI global (2022) equations", not 2012, right?

**Comment by thlytras** [comment]
Yes indeed. But I think what you point out in Bowerman et al's supplement must be a typo of some kind; I went back to the original paper describing the LMS method (doi: 10.1002/sim.4780111005) and clearly the correct equation is ((O/E)^L - 1)/(L*S) for L<>0, not (O-E)^(L - 1)/(L*S).

**Comment by Jiangnanlyu** [comment]
Thank you for your explanation! It is very helpful.
