### ISSUE TITLE
A warning message about gender 

### ISSUE THREAD

**Issue by supermaheroo** [thlytras/rspiro#2]
Hi. thanks for developing this package. I am trying to predict some PFT values and I am getting this message. 

Warning message:
You have specified more than two unique values for gender. Please check your data. Returning NA. 

even though I have my gender as "1" and "2"

Maher,

**Comment by thlytras** [comment]
Assuming dat$gender is your vector, please try:
```
class(dat$gender)
table(dat$gender)
```
If you get this warning message, you really do have more than two unique values for gender.
Set up your vector as an integer, and make sure it's only 1 or 2.

**Comment by supermaheroo** [comment]
Hi again 

it is still given me the same error

> class(d2$sexforGLI)
[1] "integer"
> table(d2$sexforGLI)

  0   1 
166 227

**Comment by thlytras** [comment]
You need to code your integer NOT as 0/1, but 1/2.

Στις Τρί, 5 Νοε 2019, 14:57 ο χρήστης Maher AlQuaimi <
notifications@github.com> έγραψε:

**Comment by supermaheroo** [comment]
It worked. Thanks a lot.
