### ISSUE TITLE
FEV1FVC definition in pctptred_GLI help wrong

### ISSUE THREAD

**Issue by nshrine** [thlytras/rspiro#3]
In the help for pctpred_GLI help it specifies the argument:

FEV1FVC          FEV1 / FVC * 100%

but it is actually just FEV1/FVC (range 0-1) that is the required argument, not *100%

presumably the same for FEV075FVC argument but not checked this

**Comment by thlytras** [comment]
You're correct, thank you. Fixed in the latest commit.
