### ISSUE TITLE
Z-scores for NHANES3

### ISSUE THREAD

**Issue by jwitonsky** [thlytras/rspiro#5]
Thank you for package. I would very much appreciate the addition of z-score calculations for NHANES3 predictions.

**Comment by thlytras** [comment]
Thank you for your comment - this is now implemented from commit 0324b5b4059138baff914c4e77ceffc4fbd3929f onwards in function zscore_NHANES3().
Note that z-score calculations would be strictly correct only for FEV1, FVC, PEF and FEV6 -- residuals for FEF2575, FEV1FVC and FEV1FEV6 are not normally distributed, though the function assumes normality for those as well.

**Comment by jwitonsky** [comment]
Thank you.

FYI, I cited your package in a recently published paper, PMID: 35033507

Best,
Jon

________________________________
